name:                zyre2
version:             0.1.0.3
github:              "skrioify/haskell-zyre2"
license:             MIT
author:              "Emil Nylind"
maintainer:          "emil@nylind.se"
copyright:           "2022 Emil Nylind"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Haskell zyre bindings for reliable group messaging over local area networks.
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/skrioify/haskell-zyre2#readme>

dependencies:
- base >= 4.7 && < 5
- inline-c >= 0.9.1 && < 0.10
- containers >= 0.6.5 && < 0.7
- text >= 1.2.4 && < 1.3
- bytestring >= 0.10.12 && < 0.11

library:
  source-dirs: src
  extra-lib-dirs:
  - /usr/local/lib
  extra-libraries: 
  - zyre
  - czmq
  exposed-modules:
  - Network.Zyre2
  - Network.Zyre2.Configuration

executables:
  zyre-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zyre2

tests:
  zyre2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zyre2

